### PR TITLE
Graphql fronts test

### PR DESCRIPTION
**Pull request by fredex42**
> [!WARNING]
> This PR is not intended for immediate merge and is not based off main. 
> It's intended to show the current process for adding a query and to isolate testing work from the POC cleanup

## What does this change?

- Updates the graphql schema, taking into account https://github.com/guardian/feast-unified-api/pull/22 and https://github.com/guardian/feast-unified-api/pull/14
- Adds the "fetch curation" query we developed together as a group (requires https://github.com/guardian/feast-unified-api/pull/29 on the server side to work)
- Exposes via a new function `getCurationForTest` on `recipeRepository`

## How to test

- Get this branch locally
- Build the xcframeworks for iOS (@tkgnm or @shamoon-guardian can you fill in the steps to do this?)
- Link into the iOS project, set up the library to point to CODE
- Ensure that https://github.com/guardian/feast-unified-api/pull/29 is deployed to CODE
- Test it

## How can we measure success?

Able to conduct further integration testing on iOS, to understand the scale of work to bring the data out to the render layer

## Have we considered potential risks?

n/a

### CODE REVIEW

**Comment by tkgnm** [comment]
@fredex42 @shamoon-guardian I'm trying to use the "debug" version of the three xcframework's to see if it makes debugging easier when using breakpoints and lldb

Unfortunately, it's not compiling when I use those versions, and I don't quite understand why... but Claude seems to know what's going wrong. Posting its summary below...

@ -0,0 +1,52 @@
# iOS: avoiding duplicate-symbol linker errors

## Symptom

Linking a Swift app against the **debug** XCFrameworks fails with hundreds/thousands of:

```
duplicate symbol '_kfun:kotlin...' in:
    .../FeastMultiplatformNetworking(...libstdlib-cache.a.o)
    .../FeastMultiplatformGraphQL(...libstdlib-cache.a.o)
    .../FeastMultiplatformAPI(...libstdlib-cache.a.o)
```

## Cause

Each core module (`:core:networking`, `:core:graphql`, `:core:api`) is built as a
**static** Kotlin/Native framework (`isStatic = true`). A static KMP framework links
*all* of its dependencies — including the Kotlin runtime + stdlib — into its own
binary.

- In **debug**, Kotlin/Native links the pre-built stdlib cache
  (`libstdlib-cache.a.o`) with no dead-code elimination, so every framework carries
  the full, identical stdlib. Linking more than one at once => duplicate symbols.
- In **release**, the stdlib is recompiled inline with DCE, which usually trims
  enough overlap to link — but this only masks the same underlying design issue.

## Fix (recommended): link only one umbrella framework on iOS

`FeastMultiplatformAPI` already contains the compiled code of `:core:graphql`,
`:core:networking`, and the stdlib inside its single binary. It now also
`export`s those modules, so their public API is visible through it.

**On iOS, add only the `FeastMultiplatformAPI` XCFramework / SPM package.**
Do **not** also add `FeastMultiplatformGraphQL` or `FeastMultiplatformNetworking`
— importing `FeastMultiplatformAPI` gives you their public API too.

```swift
import FeastMultiplatformAPI
// graphql + networking public types are available via this one import
```

Note: Android (JVM) is unaffected — the shared classpath deduplicates the stdlib,
so you can keep depending on the individual `-android` Maven artifacts there.

## Alternative: dynamic frameworks

If you genuinely need to link the frameworks separately, set `isStatic = false`
on each module. Dynamic frameworks keep the stdlib in separate dylibs instead of
statically merging it into the app binary, which removes the duplicate-symbol
link error (at the cost of larger overall size and multiple runtime copies).
The umbrella approach above is preferred.

**Comment by fredex42** [comment]
SKIE import is properly implemented in #149 ; the rest is testing, and not intended for merge
